lib/jira_web/router.ex
defmodule JiraWeb.Router do
  use JiraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {JiraWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :set_current_user
  end

  pipeline :auth do
    plug :check_current_user
  end

  def set_current_user(conn, _params) do
    current_user = get_session(conn, :current_user)
    assign(conn, :current_user, current_user)
  end

  def check_current_user(conn, _opts) do
    if conn.assigns[:current_user] do
      conn
    else
      conn
      |> put_flash(:error, "Please login")
      |> redirect(to: "/login")
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", JiraWeb do
    pipe_through :browser

    get "/", PageController, :home
    get "/register", RegistrationController, :form
    post "/register", RegistrationController, :register
    get "/login", AuthController, :form
    post "/login", AuthController, :login
    delete "/logout", AuthController, :logout

    pipe_through :auth

    resources "/projects", ProjectController, except: [:show] do
      resources "/tasks", TaskController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", JiraWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:jira, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: JiraWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/jira_web/components/layouts/app.html.heex
<header class="px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between border-b border-zinc-100 py-3 text-sm">
    <div class="flex items-center gap-4">
      <a href="/">
        <img src={~p"/images/logo.svg"} width="36" />
      </a>
    </div>
    <div class="flex items-center gap-4 font-semibold leading-6 text-zinc-900">
      <div class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li>
              <%= @current_user.login %>
            </li>
            <li>
              <%= link("Log out", to: auth_path(@conn, :logout), method: "delete") %>
            </li>
          <% else %>
            <li>
              <%= link("register", to: registration_path(@conn, :form)) %>
            </li>
            <li>
              <%= link("log in", to: auth_path(@conn, :form)) %>
            </li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </div>
    </div>
  </div>
</header>
<main class="px-4 py-20 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-2xl">
    <.flash_group flash={@flash} />
    <%= @inner_content %>
  </div>
</main>

lib/jira_web/components/layouts/root.html.heex
<!DOCTYPE html>
<html lang="en" class="[scrollbar-gutter:stable]">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Phoenix Framework">
      <%= assigns[:page_title] || "Jira" %>
    </.live_title>
    <link phx-track-static rel="stylesheet" href={~p"/assets/app.css"} />
    <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}>
    </script>
  </head>
  <body class="bg-white antialiased">
    <%= @inner_content %>
  </body>
</html>